### ISSUE TITLE
No Such Exports startPlayerCustomization

### ISSUE THREAD

**Issue by shruog** [snakewiz/fivem-appearance#1] opened 2021-03-25 18:56 UTC
I just downloaded the latest version of the script and I'm getting this error what can it be?

![image](https://user-images.githubusercontent.com/63626404/112528151-8e718000-8d82-11eb-97f5-4a592ab607a2.png)

**Comment by snakewiz** [comment] 2021-03-27 00:16
Hi, I wasn't able to reproduce your issue on my end. Could be something related to resource start order, always start the resource that is consuming the exports after the one that register the export. Also, make sure that the resource's name is correct, sometimes you could have renamed the fivem-appearance folder and have not updated the code.

**Comment by JoeriAben** [comment] 2021-03-28 21:39
You need to run the `yarn build:game` command or if you wanna use the UI aswell `yarn build`. Then the export will be available

**Comment by snakewiz** [comment] 2021-04-05 16:16
I'll be closing the issue since no one reported the same problem, and there was no new movement in the last few days.

**Closed by snakewiz** 2021-04-05 16:16 UTC

**Comment by TheAimWolf** [comment] 2021-04-14 16:51
Hey, sorry but I have the same problem. I tryed to rebuild the project. But Yarn says:

`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'`

when I try to run:

`yarn build`

inside of the main directory of the script. Also I don't really get what the docs are saying about ConVars. It says that I have to write

`setr fivem-appearance:customization 1
ensure fivem-appearance`

in a config.cfg, if I want to use the exports. But I don't know where I should create the config.cfg, or where I should execute these commands. I tried it in the fivem console, and it gave me no error, but also no response that the variables where set. And yes, I started the my test resource after the apperace script.

Btw, really nice release, I hope that you can help me, so I can use your awsome work too ❤️

**Comment by JoeriAben** [comment] 2021-04-14 17:03
It is `yarn run build`

**Comment by TheAimWolf** [comment] 2021-04-14 17:27
Ok so I figured some things out: Yarn is working better on Windows then on Linux and you shouldn't build things in vs code. Now the project trys to build, but I get a build failure. The log is so long that I can't paste it in completly, but the beginning looks like this:
`yarn run v1.22.10
$ yarn build:game && yarn build:ui
$ cd typescript && yarn && yarn build
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ webpack --mode production
asset client.js 20.3 KiB [emitted] [minimized] (name: main)
runtime modules 221 bytes 1 module
modules by path ./src/client/*.ts 20.4 KiB
  ./src/client/index.ts 12 KiB [built] [code generated]
  ./src/client/constants.ts 8.35 KiB [built] [code generated]
modules by path ./src/client/modules/customization/*.ts 16.7 KiB
  ./src/client/modules/customization/index.ts 12 KiB [built] [code generated]
  ./src/client/modules/customization/nui.ts 4.71 KiB [built] [code generated]
./src/client/utils/index.ts 750 bytes [built] [code generated]
webpack 5.32.0 compiled successfully in 3307 ms
$ cd ui && yarn && yarn build
info No lockfile found.
[1/4] Resolving packages...
warning react-scripts > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-scripts > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > resolve-url-loader > rework > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > resolve-url-loader > rework > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning react-scripts > workbox-webpack-plugin > workbox-build > rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-scripts > jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning react-scripts > jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > styled-components@5.2.3" has unmet peer dependency "react-is@>= 16.8.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ cross-env REACT_APP_ENV=production react-scripts build
Creating an optimized production build...
Failed to compile.

src\App.tsx
  Line 1:53:   Insert `␍`  prettier/prettier
  Line 2:44:   Insert `␍`  prettier/prettier
  Line 3:1:    Insert `␍`  prettier/prettier
  Line 4:50:   Insert `␍`  prettier/prettier
  Line 5:1:    Insert `␍`  prettier/prettier
  Line 6:30:   Insert `␍`  prettier/prettier
  Line 7:11:   Insert `␍`  prettier/prettier
  Line 8:23:   Insert `␍`  prettier/prettier
  Line 9:21:   Insert `␍`  prettier/prettier
  Line 10:23:  Insert `␍`  prettier/prettier
  Line 11:24:  Insert `␍`  prettier/prettier
  Line 12:5:   Insert `␍`  prettier/prettier
  Line 13:3:   Insert `␍`  prettier/prettier
  Line 14:1:   Insert `␍`  prettier/prettier
  Line 15:20:  Insert `␍`  prettier/prettier

src\Nui.ts
  Line 1:32:   Insert `␍`  prettier/prettier
  Line 2:1:    Insert `␍`  prettier/prettier
  Line 3:19:   Insert `␍`  prettier/prettier
  Line 4:22:   Insert `␍`  prettier/prettier
  Line 5:2:    Insert `␍`  prettier/prettier
  Line 6:1:    Insert `␍`  prettier/prettier
  Line 7:50:   Insert `␍`  prettier/prettier
  Line 8:1:    Insert `␍`  prettier/prettier
  Line 9:27:   Insert `␍`  prettier/prettier
  Line 10:1:   Insert `␍`  prettier/prettier
  Line 11:62:  Insert `␍`  prettier/prettier
  Line 12:52:  Insert `␍`  prettier/prettier
  Line 13:31:  Insert `␍`  prettier/prettier
  Line 14:1:   Insert `␍`  prettier/prettier
  Line 15:31:  Insert `␍`  prettier/prettier
  Line 16:4:   Insert `␍`  prettier/prettier
  Line 17:1:   Insert `␍`  prettier/prettier
  Line 18:61:  Insert `␍`  prettier/prettier
  Line 19:1:   Insert `␍`  prettier/prettier
  Line 20:38:  Insert `␍`  prettier/prettier
  Line 21:20:  Insert `␍`  prettier/prettier
  Line 22:15:  Insert `␍`  prettier/prettier
  Line 23:57:  Insert `␍`  prettier/prettier
  Line 24:7:   Insert `␍`  prettier/prettier
  Line 25:32:  Insert `␍`  prettier/prettier
  Line 26:6:   Insert `␍`  prettier/prettier
  Line 27:1:   Insert `␍`  prettier/prettier
  Line 28:26:  Insert `␍`  prettier/prettier
  Line 29:2:   Insert `␍`  prettier/prettier
  Line 30:1:   Insert `␍`  prettier/prettier
  Line 31:50:  Insert `␍`  prettier/prettier
  Line 32:22:  Insert `␍`  prettier/prettier
  Line 33:61:  Insert `␍`  prettier/prettier
  Line 34:12:  Insert `␍`  prettier/prettier
  Line 35:4:   Insert `␍`  prettier/prettier
  Line 36:23:  Insert `␍`  prettier/prettier
  Line 37:2:   Insert `␍`  prettier/prettier
  Line 38:1:   Insert `␍`  prettier/prettier
  Line 39:55:  Insert `␍`  prettier/prettier
  Line 40:24:  Insert `␍`  prettier/prettier
  Line 41:34:  Insert `␍`  prettier/prettier
  Line 42:31:  Insert `␍`  prettier/prettier
  Line 43:8:   Insert `␍`  prettier/prettier
  Line 44:5:   Insert `␍`  prettier/prettier
  Line 45:2:   Insert `␍`  prettier/prettier
  Line 46:1:   Insert `␍`  prettier/prettier
  Line 47:42:  Insert `␍`  prettier/prettier
  Line 48:1:   Insert `␍`  prettier/prettier
  Line 49:20:  Insert `␍`  prettier/prettier
  Line 50:1:   Insert `␍`  prettier/prettier
  Line 51:37:  Insert `␍`  prettier/prettier
  Line 52:60:  Insert `␍`  prettier/prettier
  Line 53:38:  Insert `␍`  prettier/prettier
  Line 54:41:  Insert `␍`  prettier/prettier
  Line 55:6:   Insert `␍`  prettier/prettier
  Line 56:1:   Insert `␍`  prettier/prettier
  Line 57:15:  Insert `␍`  prettier/prettier
  Line 58:3:   Insert `␍`  prettier/prettier

src\components\Appearance\Components.tsx
  Line 1:52:    Insert `␍`  prettier/prettier
  Line 2:1:     Insert `␍`  prettier/prettier
  Line 3:44:    Insert `␍`  prettier/prettier
...
`
Do you suggest to switch to an other branche? Or should I build from the release? Thanks for you quick response!

**Comment by Trsak** [comment] 2021-06-03 12:17
Hey @TheAimWolf, did you manage to fix issue with build? Having same errors

**Comment by TheAimWolf** [comment] 2021-06-03 15:01
Nope. I gave up, after I tried to build it on diffrent operating systems and building envoirments. I always get the same errors. Maybe the builder of this project can tell us what they use to successfully build this project, or give us some advice how to build it properly. If this would work, it would be one of the best char creators i saw.
